version: '3.9'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: herambdb
      MYSQL_USER: krishna
      MYSQL_PASSWORD: Krishna@123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 10
  backend:
    build: ./backend
    command: npm run dev
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    ports:
      - '4000:4000'
    depends_on:
      db:
        condition: service_healthy
  frontend:
    build: ./frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    depends_on:
      - backend
volumes:
  dbdata:
